from .category_prompts import (
    DEFAULT_CATEGORY_PROMPTS,
    FALCON_CATEGORY_PROMPTS,
    DOTS_MOCR_CATEGORY_PROMPTS,
    DOTS_MOCR_PROMPT_OCR,
    DOTS_MOCR_PROMPT_LAYOUT_ALL_EN,
    DOTS_MOCR_PROMPT_LAYOUT_ONLY_EN,
    DOTS_MOCR_PROMPT_IMAGE_TO_SVG,
    DOTS_MOCR_PROMPT_GROUNDING_OCR,
    DOTS_MOCR_PROMPT_SCENE_SPOTTING,
    DOTS_MOCR_PROMPT_WEB_PARSING,
    DOTS_MOCR_PROMPT_GENERAL,
)

__all__ = [
    "DEFAULT_CATEGORY_PROMPTS",
    "FALCON_CATEGORY_PROMPTS",
    "DOTS_MOCR_CATEGORY_PROMPTS",
    "DOTS_MOCR_PROMPT_OCR",
    "DOTS_MOCR_PROMPT_LAYOUT_ALL_EN",
    "DOTS_MOCR_PROMPT_LAYOUT_ONLY_EN",
    "DOTS_MOCR_PROMPT_IMAGE_TO_SVG",
    "DOTS_MOCR_PROMPT_GROUNDING_OCR",
    "DOTS_MOCR_PROMPT_SCENE_SPOTTING",
    "DOTS_MOCR_PROMPT_WEB_PARSING",
    "DOTS_MOCR_PROMPT_GENERAL",
]
